In [1]:
import os
import tensorflow as tf

2025-05-25 15:26:05.368570: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-05-25 15:26:05.387049: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1748204765.409210   65881 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748204765.415662   65881 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1748204765.432244   65881 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [2]:
# Initialization
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

x = tf.eye(3)
print(x)

x = tf.ones((4, 3))
print(x)

x = tf.zeros((3, 2, 5))
print(x)

x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

x = tf.random.normal((3, 3), mean=0, stddev=1)
print(tf.cast(x, dtype=tf.float64))
# tf.float (16,32,64), tf.int (8, 16, 32, 64), tf.bool

x = tf.range(9)
x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)
tf.Tensor(
[[0.46774542 0.7549226 ]
 [0.7652079  0.46176362]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.84456491 -0.69404107 -0.04239392]
 [ 0.55747736  0.57785803  1.54807353]
 [-0.98095816 -0.42478749 -0.05582712]], shape=(3, 3), dtype=float64)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


2025-05-25 15:26:09.475016: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [3]:
# Math
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

print(f"x = {x}")
print(f"y = {y}")

z = tf.add(x, y)
z = x + y
print(f"x+y = {z}")

z = tf.subtract(x, y)
z = x - y
print(f"x-y = {z}")

z = tf.divide(x, y)
z = x / y
print(f"x/y = {z}")

z = tf.multiply(x, y)
z = x * y
print(f"x*y = {z}")

z = tf.tensordot(x, y, axes=1)
print(f"x dot y  = {z}")

z = x ** 5
print(f"x^5  = {z}")

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
z = tf.matmul(x, y)
z = x @ y
print(f"x @ y  = {z}")

x = tf.random.normal((2, 2))
print(f"rand normal 2x2 tensor  = {z}")

x = [1 2 3]
y = [9 8 7]
x+y = [10 10 10]
x-y = [-8 -6 -4]
x/y = [0.11111111 0.25       0.42857143]
x*y = [ 9 16 21]
x dot y  = 46
x^5  = [  1  32 243]
x @ y  = [[ 0.2772769   2.062826  ]
 [-2.5603497   0.71413875]]
rand normal 2x2 tensor  = [[ 0.2772769   2.062826  ]
 [-2.5603497   0.71413875]]


In [4]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)

x = tf.constant([[1, 2], [3, 4], [5, 6]])

print(x[0, :])
print(x[0:2, :])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [5]:
# Reshaping
x = tf.range(9)
print(f"x={x}")

x = tf.reshape(x, (3, 3))
print(f"x reshaped to 3x3 tensor = \n{x}")

x = tf.transpose(x, perm=[1, 0])
print(f"x transposed = \n{x}")

x=[0 1 2 3 4 5 6 7 8]
x reshaped to 3x3 tensor = 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
x transposed = 
[[0 3 6]
 [1 4 7]
 [2 5 8]]


2025-05-25 15:26:27.652613: E tensorflow/core/util/util.cc:131] oneDNN supports DT_INT32 only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.
